---
AWSTemplateFormatVersion: 2010-09-09

Description: Stack to learn how to cascade templates.

Resources:
  vpc: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-163atm1ydoza8-us-west-2/learning-cfn-00-newvpc.yaml

  ec2:
    Type: AWS::CloudFormation::Stack
    DependsOn: [newvpc, securitygroups ]
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-163atm1ydoza8-us-west-2/learning-cfn-02-ec2.yaml

  securitygroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-163atm1ydoza8-us-west-2/learning-cfn-03-securitygroup.yaml

Parameters:
  InstTypeParam:
    Type: String
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Description:
      EC2 Instance Type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  SGwebdmz:
    Type: String
    Default:  
  EC2KeyName:
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair. Your bastion & Web instances will launch with this KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
  VpcTenancy:
    AllowedValues:
    - default
    - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC
    Type: String 
