Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: 'ami-035be7bafff33b6b6' # Amazon Linux AMI
      Tags:
        - Key: Name
          Value: !Join [ "", [ 'VPC /', ' Update' ] ]
      EC2KeyName:
        - Key: Name
          Value: cxa-2019-q1


