Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: 'ami-032509850cf9ee54e' # Amazon Linux AMI
      Tags:
        - Key: Name
          Value: !Join [ "", [ 'VPC /', ' Update' ] ]
      KeyName: 'cxa-2019-q1'
